# Generated by Django 4.0.5 on 2022-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('auther', models.CharField(max_length=30)),
                ('edition', models.CharField(max_length=30)),
            ],
        ),
    ]
